# Generated by Django 2.2.4 on 2019-08-27 21:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=80)),
                ('cep', models.IntegerField(max_length=9)),
            ],
        ),
    ]
